use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

use serde::Deserialize;
use sha2::{Digest, Sha256};
use walkdir::WalkDir;

#[derive(Debug, Deserialize)]
struct RulesetDocument {
    ruleset: RulesetMetadata,
}

#[derive(Debug, Deserialize)]
struct RulesetMetadata {
    game: String,
    name: String,
    repository: String,
    revision: String,
    upstream_repository: String,
    upstream_revision: String,
    source_directory: String,
    virtual_prefix: String,
    license: String,
    required_cwtools_repository: String,
    required_cwtools_revision: String,
}

#[derive(Debug)]
struct SourceFile {
    virtual_path: String,
    file_path: PathBuf,
    content: String,
}

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=ruleset.toml");

    let metadata = read_metadata(&manifest_dir)?;
    let source_root = manifest_dir.join(&metadata.source_directory);
    println!("cargo:rerun-if-changed={}", source_root.display());

    let sources = collect_sources(&metadata, &source_root)?;
    let generated = render_generated_sources(&metadata, &sources);
    fs::write(out_dir.join("hoi4_cwt_sources.rs"), generated)
}

fn read_metadata(manifest_dir: &Path) -> io::Result<RulesetMetadata> {
    let path = manifest_dir.join("ruleset.toml");
    let content = fs::read_to_string(&path)?;
    toml::from_str::<RulesetDocument>(&content)
        .map(|document| document.ruleset)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error.to_string()))
}

fn collect_sources(metadata: &RulesetMetadata, source_root: &Path) -> io::Result<Vec<SourceFile>> {
    if !source_root.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!(
                "CWT source directory does not exist: {}",
                source_root.display()
            ),
        ));
    }

    let mut sources = Vec::new();
    let virtual_prefix = metadata.virtual_prefix.trim_end_matches('/');

    for entry in WalkDir::new(source_root).sort_by_file_name() {
        let entry = entry.map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("walkdir error: {error}"),
            )
        })?;
        if !entry.file_type().is_file() {
            continue;
        }

        let path = entry.into_path();
        if !path
            .extension()
            .and_then(|extension| extension.to_str())
            .is_some_and(|extension| extension.eq_ignore_ascii_case("cwt"))
        {
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());
        let relative_path = path
            .strip_prefix(source_root)
            .map_err(|error| io::Error::new(io::ErrorKind::InvalidInput, error.to_string()))?;
        let relative_path = relative_path.to_string_lossy().replace('\\', "/");
        let virtual_path = format!("{virtual_prefix}/{relative_path}");
        let content = fs::read_to_string(&path)?;
        sources.push(SourceFile {
            virtual_path,
            file_path: path,
            content,
        });
    }

    sources.sort_by(|left, right| left.virtual_path.cmp(&right.virtual_path));
    if sources.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("no .cwt files found in {}", source_root.display()),
        ));
    }

    Ok(sources)
}

fn render_generated_sources(metadata: &RulesetMetadata, sources: &[SourceFile]) -> String {
    let total_bytes = sources
        .iter()
        .map(|source| source.content.len())
        .sum::<usize>();
    let content_sha256 = content_sha256(sources);

    let mut output = String::from("// This file is generated by build.rs.\n");
    push_const_str(&mut output, "GAME", &metadata.game);
    push_const_str(&mut output, "NAME", &metadata.name);
    push_const_str(&mut output, "REPOSITORY", &metadata.repository);
    push_const_str(&mut output, "REVISION", &metadata.revision);
    push_const_str(
        &mut output,
        "UPSTREAM_REPOSITORY",
        &metadata.upstream_repository,
    );
    push_const_str(
        &mut output,
        "UPSTREAM_REVISION",
        &metadata.upstream_revision,
    );
    push_const_str(&mut output, "SOURCE_DIRECTORY", &metadata.source_directory);
    push_const_str(&mut output, "VIRTUAL_PREFIX", &metadata.virtual_prefix);
    push_const_str(&mut output, "LICENSE", &metadata.license);
    push_const_str(
        &mut output,
        "REQUIRED_CWTOOLS_REPOSITORY",
        &metadata.required_cwtools_repository,
    );
    push_const_str(
        &mut output,
        "REQUIRED_CWTOOLS_REVISION",
        &metadata.required_cwtools_revision,
    );
    push_const_str(&mut output, "CONTENT_SHA256", &content_sha256);
    output.push_str(&format!(
        "pub const SOURCE_COUNT: usize = {};\n",
        sources.len()
    ));
    output.push_str(&format!("pub const TOTAL_BYTES: usize = {total_bytes};\n"));
    output.push_str("pub const SOURCES: &[crate::CwtSource] = &[\n");

    for source in sources {
        output.push_str("    crate::CwtSource { path: ");
        output.push_str(&rust_string_literal(&source.virtual_path));
        output.push_str(", content: include_str!(");
        output.push_str(&rust_string_literal(&source.file_path.to_string_lossy()));
        output.push_str(") },\n");
    }

    output.push_str("];\n");
    output
}

fn content_sha256(sources: &[SourceFile]) -> String {
    let mut hasher = Sha256::new();

    for source in sources {
        hasher.update(source.virtual_path.as_bytes());
        hasher.update([0_u8]);
        hasher.update(source.content.as_bytes());
        hasher.update([0_u8]);
    }

    format!("{:x}", hasher.finalize())
}

fn push_const_str(output: &mut String, name: &str, value: &str) {
    output.push_str("pub const ");
    output.push_str(name);
    output.push_str(": &str = ");
    output.push_str(&rust_string_literal(value));
    output.push_str(";\n");
}

fn rust_string_literal(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() => {
                output.push_str(&format!("\\u{{{:x}}}", character as u32));
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}
