[ruleset]
game = "hoi4"
name = "cwtools-hoi4-config"
repository = "https://github.com/Hilde-Research-Foundation/cwtools-hoi4-config-rs"
source_directory = "Config"
virtual_prefix = "cwtools-hoi4-config/config"
license = "MIT"
revision = "bd23ac76aa6929ab7e1b20d39345c0e7e5d1b919"
upstream_repository = "https://github.com/Kaiserreich/cwtools-hoi4-config"
upstream_revision = "580703ae5a2edd1b96b3ec3095f55570f6a05c34"
required_cwtools_repository = "https://github.com/MillenniumDawn/cwtools"
required_cwtools_revision = "cb7f8c8c95dd68fcbd06d37efb87bc49fc17fbef"
